modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Tabula/issues"

[[mods]]
    modId="tabula"
    version="${file.jarVersion}" #mandatory
    displayName="Tabula"
    displayURL="http://ichun.me/mods/tabula-minecraft-modeler/"
    authors="iChun"
    description='''
    A successor to the modeler Techne, an in-game modeler with SMP support.
    '''

[[dependencies.tabula]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.5.1,11)"
    ordering="NONE"
    side="BOTH"
